# generated by datamodel-codegen:
#   filename:  openapi-public.json

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class CaptureHistoryEntry(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    capture_id: str
    capture_time: str
    content_digest: str
    content_format: str | None = None


class ContentRange(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    capture_id: str | None = None
    """
    Optional capture pin; a stale_range warning is returned when the latest capture differs.
    """
    max_chars: int | None = Field(None, ge=1)
    """
    Maximum characters for this range; overrides content.max_chars.
    """
    start_char: int | None = Field(None, ge=0)
    """
    Character offset to start content from.
    """


class Document(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    canonical_url: str
    content_digest: str | None = None
    doc_id: str
    first_seen_at: str
    headings: list[str] | None = None
    last_seen_at: str
    latest_capture_id: str | None = None
    meta_description: str | None = None
    published_at: str | None = None
    source_url: str
    title: str | None = None


class DocumentContent(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    char_count: int
    format: str
    selection: str
    start_char: int | None = None
    text: str
    truncated: bool


class Format(Enum):
    """
    Returned content format.
    """

    text = "text"
    markdown = "markdown"


class Selection(Enum):
    """
    Content selection strategy.
    """

    none = "none"
    query_relevant = "query_relevant"
    top_passages = "top_passages"
    passage_ids = "passage_ids"
    full_document = "full_document"


class DocumentContentRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    format: Format | None = "markdown"
    """
    Returned content format.
    """
    include_offsets: bool | None = None
    """
    Whether passage offsets should be included when available.
    """
    max_chars: int | None = Field(12000, ge=1)
    """
    Maximum content.text characters to return.
    """
    passage_ids: list[str] | None = None
    """
    Passage IDs to return when selection is passage_ids.
    """
    range: ContentRange | None = None
    """
    Continuation read: return content starting at a character offset of the same document.
    """
    selection: Selection | None = "query_relevant"
    """
    Content selection strategy.
    """


class DocumentProvenance(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    capture_id: str
    capture_time: str


class IncludeEnum(Enum):
    metadata = "metadata"
    passages = "passages"
    capture_history = "capture_history"
    content = "content"


class DocumentRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=[
            "https://search-api-staging-779189860552.europe-west1.run.app/DocumentRequest.json"
        ],
    )
    """
    A URL to the JSON Schema for this object.
    """
    canonical_url: AnyUrl | None = None
    """
    Canonical URL lookup key. Either doc_id or canonical_url is required.
    """
    content: DocumentContentRequest | None = None
    """
    Controls for returned document content.
    """
    debug: dict[str, Any] | None = None
    """
    Optional debug controls for internal evaluation.
    """
    doc_id: UUID | None = Field(None, examples=["0c944fa8-4c8f-4f48-9b08-0fb2fd3438ec"])
    """
    Canonical document identifier. Either doc_id or canonical_url is required.
    """
    include: list[IncludeEnum] | None = None
    """
    Optional document sections to include.
    """
    query: str | None = None
    """
    Optional query context for passage selection.
    """


class ErrorBody(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: str
    """
    Stable machine-readable error code.
    """
    details: dict[str, Any] | None = None
    """
    Optional structured error details.
    """
    message: str
    """
    Human-readable error message.
    """


class Type(Enum):
    """
    Envelope discriminator.
    """

    error = "error"


class ErrorEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=[
            "https://search-api-staging-779189860552.europe-west1.run.app/ErrorEnvelope.json"
        ],
    )
    """
    A URL to the JSON Schema for this object.
    """
    error: ErrorBody
    """
    Error details.
    """
    request_id: str
    """
    Server request identifier.
    """
    type: Type
    """
    Envelope discriminator.
    """


class FeedbackAgentContext(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    client_model: str | None = None
    """
    Calling model identifier.
    """
    task_type: str | None = None
    """
    Agent task type or evaluation bucket.
    """


class EventType(Enum):
    """
    Feedback event classification.
    """

    result_helpful = "result_helpful"
    result_not_helpful = "result_not_helpful"
    passage_used = "passage_used"
    read_abandoned = "read_abandoned"
    duplicate_result = "duplicate_result"
    stale_result = "stale_result"
    spam_or_low_quality = "spam_or_low_quality"
    missing_expected_source = "missing_expected_source"
    unsafe_or_policy_issue = "unsafe_or_policy_issue"


class FeedbackRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=[
            "https://search-api-staging-779189860552.europe-west1.run.app/FeedbackRequest.json"
        ],
    )
    """
    A URL to the JSON Schema for this object.
    """
    agent_context: FeedbackAgentContext | None = None
    """
    Optional calling-agent context.
    """
    doc_id: UUID | None = None
    """
    Document associated with the feedback event.
    """
    event_type: EventType
    """
    Feedback event classification.
    """
    notes: str | None = None
    """
    Optional notes for human review or offline evaluation.
    """
    passage_id: UUID | None = None
    """
    Passage associated with the feedback event.
    """
    query: str | None = None
    """
    Query associated with the feedback event.
    """
    rank: int | None = Field(None, ge=1)
    """
    One-based result rank, when applicable.
    """
    search_id: UUID | None = None
    """
    Search request identifier returned by /v1/search.
    """
    session_id: UUID | None = None
    """
    Optional client session identifier.
    """


class Passage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    char_end: int | None = None
    char_start: int | None = None
    doc_id: str
    ordinal: int
    passage_id: str
    section_heading: str | None = None
    section_path: list[str] | None = None
    text: str


class Ranking(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: str
    ranker_version: str
    score_scope: str


class RateLimit(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    limit_rps: int
    remaining: int
    reset_at: str


class OnExceed(Enum):
    """
    What to do when the budget binds: shed payload in the documented order, or fail with response_too_large.
    """

    shed = "shed"
    error = "error"


class ResponseBudget(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    max_chars_total: int | None = Field(None, ge=1)
    """
    Maximum serialized response size in characters. Roughly 4 characters per token.
    """
    on_exceed: OnExceed | None = "shed"
    """
    What to do when the budget binds: shed payload in the documented order, or fail with response_too_large.
    """


class Verbosity(Enum):
    """
    Field preset: ids_only (rank, doc_id, url, title), compact (adds snippet, score, key dates), standard (today's default), full (adds provenance).
    """

    ids_only = "ids_only"
    compact = "compact"
    standard = "standard"
    full = "full"


class ResponseShape(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    budget: ResponseBudget | None = None
    """
    Total serialized response budget in characters with deterministic shedding.
    """
    verbosity: Verbosity | None = "standard"
    """
    Field preset: ids_only (rank, doc_id, url, title), compact (adds snippet, score, key dates), standard (today's default), full (adds provenance).
    """


class Mode(Enum):
    """
    Retrieval budget and ranking mode.
    """

    fast = "fast"
    standard = "standard"
    research = "research"


class SearchRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=[
            "https://search-api-staging-779189860552.europe-west1.run.app/SearchRequest.json"
        ],
    )
    """
    A URL to the JSON Schema for this object.
    """
    client_model: str | None = None
    """
    Optional calling model identifier for analytics and tuning.
    """
    content: dict[str, Any] | None = None
    """
    Optional content-return controls.
    """
    debug: dict[str, Any] | None = None
    """
    Optional debug controls for internal evaluation.
    """
    filters: dict[str, Any] | None = None
    """
    Optional structured filters.
    """
    freshness_policy: dict[str, Any] | None = None
    """
    Optional freshness requirements for time-sensitive queries.
    """
    max_results: int | None = Field(10, ge=1, le=50)
    """
    Maximum number of ranked results to return.
    """
    mode: Mode | None = "standard"
    """
    Retrieval budget and ranking mode.
    """
    objective: str | None = None
    """
    Optional task objective used by agents to shape retrieval.
    """
    query: str = Field(..., examples=["linux kernel amd gpu suspend"], min_length=1)
    """
    Original user or agent query.
    """
    response: ResponseShape | None = None
    """
    Optional response shaping: verbosity preset and serialized-size budget.
    """
    search_queries: list[str] | None = None
    """
    Optional caller-provided query rewrites.
    """
    session_id: UUID | None = None
    """
    Optional client session identifier.
    """
    source_policy: dict[str, Any] | None = None
    """
    Optional source inclusion and exclusion policy.
    """


class SearchResultMetadata(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content_digest: str | None = None
    extracted_at: str | None = None
    first_seen_at: str | None = None
    last_crawled_at: str | None = None
    last_seen_at: str | None = None
    published_at: str | None = None


class SearchScore(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    value: float


class Usage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    approx_tokens: int
    bytes_returned: int
    requests: int


class Warning(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: str
    details: dict[str, Any] | None = None
    message: str


class Access(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    rate_limit: RateLimit
    tier: str


class DocumentResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=[
            "https://search-api-staging-779189860552.europe-west1.run.app/DocumentResponse.json"
        ],
    )
    """
    A URL to the JSON Schema for this object.
    """
    access: Access
    capture_history: list[CaptureHistoryEntry] | None = None
    content: DocumentContent | None = None
    doc: Document
    passages: list[Passage] | None = None
    provenance: DocumentProvenance | None = None
    request_id: str
    session_id: str
    usage: Usage | None = None
    warnings: list[Warning] | None = None


class FeedbackResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=[
            "https://search-api-staging-779189860552.europe-west1.run.app/FeedbackResponse.json"
        ],
    )
    """
    A URL to the JSON Schema for this object.
    """
    accepted: bool
    access: Access
    feedback_id: str
    request_id: str
    session_id: str
    usage: Usage | None = None


class SearchResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    canonical_url: str
    description: str | None = None
    doc_id: str
    metadata: SearchResultMetadata | None = None
    passages: list[Passage] | None = None
    provenance: DocumentProvenance | None = None
    rank: int
    score: SearchScore | None = None
    snippet: str | None = None
    source_url: str | None = None
    title: str | None = None


class SearchResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=[
            "https://search-api-staging-779189860552.europe-west1.run.app/SearchResponse.json"
        ],
    )
    """
    A URL to the JSON Schema for this object.
    """
    access: Access | None = None
    ranking: Ranking | None = None
    request_id: str
    results: list[SearchResult] | None
    search_id: str
    session_id: str
    truncated: bool | None = None
    usage: Usage | None = None
    warnings: list[Warning] | None = None
