# generated by datamodel-codegen:
#   filename:  openapi-public.json

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class CaptureHistoryEntry(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    capture_id: str
    capture_time: str
    content_digest: str
    content_format: str | None = None


class Citation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    index: int
    title: str
    url: str


class ContentRange(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    capture_id: str | None = None
    """
    Optional capture pin; a stale_range warning is returned when the latest capture differs.
    """
    max_chars: int | None = Field(None, ge=1)
    """
    Maximum characters for this range; overrides content.max_chars.
    """
    start_char: int | None = Field(None, ge=0)
    """
    Character offset to start content from.
    """


class Document(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    canonical_url: str
    content_digest: str | None = None
    doc_id: str
    first_seen_at: str
    headings: list[str] | None = None
    last_seen_at: str
    latest_capture_id: str | None = None
    meta_description: str | None = None
    published_at: str | None = None
    source_url: str
    title: str | None = None


class DocumentContent(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    char_count: int
    format: str
    selection: str
    start_char: int | None = None
    text: str
    truncated: bool


class Format(Enum):
    """
    Returned content format: markdown (default) preserves document structure (headings, lists, code blocks); text is plain text.
    """

    text = "text"
    markdown = "markdown"


class Selection(Enum):
    """
    How content.text is chosen: full_document (default) returns the extracted document text; query_relevant returns the passages most relevant to query; top_passages returns the document's leading passages; passage_ids returns exactly content.passage_ids; none returns no content body.
    """

    none = "none"
    query_relevant = "query_relevant"
    top_passages = "top_passages"
    passage_ids = "passage_ids"
    full_document = "full_document"


class DocumentContentRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    format: Format | None = "markdown"
    """
    Returned content format: markdown (default) preserves document structure (headings, lists, code blocks); text is plain text.
    """
    include_offsets: bool | None = None
    """
    When true, passages carry char_start/char_end offsets into the full extracted text when available, for character-precise citation.
    """
    max_chars: int | None = Field(None, ge=1)
    """
    Optional maximum content.text characters to return. Omit it for the full selected content. Longer capped reads set content.truncated true; continue with content.range.start_char instead of retrying with a larger cap.
    """
    passage_ids: list[str] | None = None
    """
    Passage identifiers to return when selection is passage_ids, from a search result's passages or a previous read.
    """
    range: ContentRange | None = None
    """
    Continuation read: return content starting at a character offset of the same document.
    """
    selection: Selection | None = "full_document"
    """
    How content.text is chosen: full_document (default) returns the extracted document text; query_relevant returns the passages most relevant to query; top_passages returns the document's leading passages; passage_ids returns exactly content.passage_ids; none returns no content body.
    """


class DocumentProvenance(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    capture_id: str
    capture_time: str


class IncludeEnum(Enum):
    metadata = "metadata"
    passages = "passages"
    capture_history = "capture_history"
    content = "content"


class DocumentRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=["https://alpha.api.trycaesar.com/DocumentRequest.json"],
    )
    """
    A URL to the JSON Schema for this object.
    """
    canonical_url: AnyUrl | None = None
    """
    Canonical URL from a result's canonical_url; lookup alternative to doc_id. Either doc_id or canonical_url is required.
    """
    content: DocumentContentRequest | None = None
    """
    Controls for returned document content: selection strategy, format, size cap, and continuation range.
    """
    debug: dict[str, Any] | None = None
    """
    Reserved for internal evaluation harnesses; ignored for public callers.
    """
    doc_id: UUID | None = Field(None, examples=["0c944fa8-4c8f-4f48-9b08-0fb2fd3438ec"])
    """
    Canonical document identifier (UUID) from a search result's doc_id; stable across searches and recrawls. Either doc_id or canonical_url is required.
    """
    include: list[IncludeEnum] | None = None
    """
    Sections to return. Omit it for everything available; otherwise an allowlist of passages, capture_history, and content (document metadata is always returned - send just metadata for a metadata-only read).
    """
    query: str | None = None
    """
    Query context for passage selection when content.selection is query_relevant.
    """


class ErrorBody(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: str
    """
    Stable machine-readable error code.
    """
    details: dict[str, Any] | None = None
    """
    Optional structured error details.
    """
    message: str
    """
    Human-readable error message.
    """


class Type(Enum):
    """
    Envelope discriminator.
    """

    error = "error"


class ErrorEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=["https://alpha.api.trycaesar.com/ErrorEnvelope.json"],
    )
    """
    A URL to the JSON Schema for this object.
    """
    error: ErrorBody
    """
    Error details.
    """
    request_id: str
    """
    Server request identifier.
    """
    type: Type
    """
    Envelope discriminator.
    """


class FeedbackAgentContext(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    client_model: str | None = None
    """
    Calling model identifier.
    """
    task_type: str | None = None
    """
    Agent task type or evaluation bucket (e.g. 'coding' or 'research').
    """


class EventType(Enum):
    """
    What happened: result_helpful / result_not_helpful (the result did or did not advance the task), passage_used (a passage was used or cited), read_abandoned (opened but abandoned), duplicate_result, stale_result (outdated content), spam_or_low_quality, missing_expected_source (a source you expected did not appear), unsafe_or_policy_issue.
    """

    result_helpful = "result_helpful"
    result_not_helpful = "result_not_helpful"
    passage_used = "passage_used"
    read_abandoned = "read_abandoned"
    duplicate_result = "duplicate_result"
    stale_result = "stale_result"
    spam_or_low_quality = "spam_or_low_quality"
    missing_expected_source = "missing_expected_source"
    unsafe_or_policy_issue = "unsafe_or_policy_issue"


class FeedbackRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=["https://alpha.api.trycaesar.com/FeedbackRequest.json"],
    )
    """
    A URL to the JSON Schema for this object.
    """
    agent_context: FeedbackAgentContext | None = None
    """
    Optional calling-agent context for slicing feedback in evaluation.
    """
    doc_id: UUID | None = None
    """
    Document the event concerns, from the result's doc_id.
    """
    event_type: EventType
    """
    What happened: result_helpful / result_not_helpful (the result did or did not advance the task), passage_used (a passage was used or cited), read_abandoned (opened but abandoned), duplicate_result, stale_result (outdated content), spam_or_low_quality, missing_expected_source (a source you expected did not appear), unsafe_or_policy_issue.
    """
    notes: str | None = None
    """
    Free-text context, recorded for human review and offline evaluation.
    """
    passage_id: UUID | None = None
    """
    Specific passage the event concerns, from passages[].passage_id; most useful with passage_used.
    """
    query: str | None = None
    """
    Query text the event relates to, useful when no search_id is available.
    """
    rank: int | None = Field(None, ge=1)
    """
    One-based position the result had in the ranked list.
    """
    search_id: UUID | None = None
    """
    The search_id returned by /v1/search. Ties feedback to the exact ranked list that produced the result, so ranking learns from the right context.
    """
    session_id: UUID | None = None
    """
    Session the event belongs to (UUID), matching session_id from earlier responses.
    """


class IntegrationResultsSummary(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    href: str
    selected: int
    total: int


class Passage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    char_end: int | None = None
    char_start: int | None = None
    doc_id: str
    ordinal: int
    passage_id: str
    section_heading: str | None = None
    section_path: list[str] | None = None
    text: str


class Ranking(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ranker_version: str
    score_scope: str


class RateLimit(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    limit_rps: int
    remaining: int
    reset_at: str


class ResearchJobSummary(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    completed_at: str | None = None
    created_at: str
    id: str
    query: str
    status: str
    """
    queued, running, completed, or failed.
    """


class ResearchRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=["https://alpha.api.trycaesar.com/ResearchRequest.json"],
    )
    """
    A URL to the JSON Schema for this object.
    """
    excluded_domains: list[str] | None = None
    """
    Domains to drop from results.
    """
    max_tool_calls: int | None = None
    """
    Max tool calls (web_search/web_read/scratchpad) before a final answer is forced. Optional; defaults internally. The agent usually stops earlier on its own.
    """
    query: str
    """
    Research question to investigate.
    """
    source_timeout: int | None = None
    """
    Per-source fetch timeout in seconds.
    """


class OnExceed(Enum):
    """
    What to do when the budget binds: shed (default) trims in a fixed order - passages, snippet tails, preset extras, then tail results, never below one result - and sets truncated plus a response_truncated warning; error fails with response_too_large instead.
    """

    shed = "shed"
    error = "error"


class ResponseBudget(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    max_chars_total: int | None = Field(None, ge=1)
    """
    Maximum serialized response size in characters (roughly 4 characters per token, so 2000 is about 500 tokens).
    """
    on_exceed: OnExceed | None = "shed"
    """
    What to do when the budget binds: shed (default) trims in a fixed order - passages, snippet tails, preset extras, then tail results, never below one result - and sets truncated plus a response_truncated warning; error fails with response_too_large instead.
    """


class Verbosity(Enum):
    """
    Field preset: ids_only (rank, doc_id, url, title), compact (adds snippet, score, key dates), standard (today's default), full (adds provenance).
    """

    ids_only = "ids_only"
    compact = "compact"
    standard = "standard"
    full = "full"


class ResponseShape(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    budget: ResponseBudget | None = None
    """
    Total serialized response budget in characters with deterministic shedding.
    """
    verbosity: Verbosity | None = "standard"
    """
    Field preset: ids_only (rank, doc_id, url, title), compact (adds snippet, score, key dates), standard (today's default), full (adds provenance).
    """


class SearchResultMetadata(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content_digest: str | None = None
    extracted_at: str | None = None
    first_seen_at: str | None = None
    last_crawled_at: str | None = None
    last_seen_at: str | None = None
    published_at: str | None = None


class SearchScope(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    indexes: list[str] | None = None
    """
    Indexes to search: web (the shared web corpus) and/or workspace (your organization's ingested documents). Default: ["web"].
    """
    workspace_id: UUID | None = None
    """
    Workspace to search; required when indexes includes workspace.
    """


class SearchScore(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    value: float


class ToolInvocation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    error: str | None = None
    latency_ms: int
    ordinal: int
    query: str | None = None
    result_count: int
    status: str
    tool: str
    turn: int
    url: str | None = None


class Usage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    bytes_returned: int
    requests: int


class Warning(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: str
    details: dict[str, Any] | None = None
    message: str


class Access(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    rate_limit: RateLimit


class DocumentResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=["https://alpha.api.trycaesar.com/DocumentResponse.json"],
    )
    """
    A URL to the JSON Schema for this object.
    """
    access: Access
    capture_history: list[CaptureHistoryEntry] | None = None
    content: DocumentContent | None = None
    doc: Document
    passages: list[Passage] | None = None
    provenance: DocumentProvenance | None = None
    request_id: str
    session_id: str
    usage: Usage | None = None
    warnings: list[Warning] | None = None


class FeedbackResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=["https://alpha.api.trycaesar.com/FeedbackResponse.json"],
    )
    """
    A URL to the JSON Schema for this object.
    """
    accepted: bool
    access: Access
    feedback_id: str
    request_id: str
    session_id: str
    usage: Usage | None = None


class IntegrationSearchResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    canonical_url: str
    description: str | None = None
    doc_id: str
    index: str | None = None
    integration: str
    labels: list[str] | None = None
    metadata: SearchResultMetadata | None = None
    mime: str | None = None
    operation: str
    passages: list[Passage] | None = None
    primary_rank: int | None = None
    provenance: DocumentProvenance | None = None
    rank: int
    score: SearchScore | None = None
    selected: bool
    snippet: str | None = None
    source_uri: str | None = None
    source_url: str | None = None
    title: str | None = None


class ResearchListResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=["https://alpha.api.trycaesar.com/ResearchListResponse.json"],
    )
    """
    A URL to the JSON Schema for this object.
    """
    access: Access | None = None
    jobs: list[ResearchJobSummary] | None
    request_id: str


class ResearchResultResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    citations: list[Citation] | None
    confidence: str
    content: str
    failure_tool: str | None = None
    failure_turn: int | None = None
    llm_calls: int
    query: str
    read_count: int
    run_id: str | None = None
    tool_calls_used: int
    tool_invocations: list[ToolInvocation] | None = None


class ResearchStartResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=["https://alpha.api.trycaesar.com/ResearchStartResponse.json"],
    )
    """
    A URL to the JSON Schema for this object.
    """
    access: Access | None = None
    id: str
    """
    Job id to poll at GET /v1/research/{id}.
    """
    request_id: str
    status: str


class SearchRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=["https://alpha.api.trycaesar.com/SearchRequest.json"],
    )
    """
    A URL to the JSON Schema for this object.
    """
    client_model: str | None = None
    """
    Calling model identifier, recorded for analytics and ranking tuning.
    """
    filters: dict[str, Any] | None = None
    """
    Structured filters. Keys: country (two-letter code such as 'us' or 'de', scoping results to a market), language (two-letter code such as 'en'), exact_match (boolean; quotes the query so the index matches it verbatim).
    """
    freshness_policy: dict[str, Any] | None = None
    """
    Recency requirements. Keys: published_after (RFC 3339 timestamp or YYYY-MM-DD date; only content published after it) and freshness (coarse window code pd, pw, pm, or py for past day, week, month, or year; ignored when published_after is set).
    """
    max_results: int | None = Field(10, ge=1, le=50)
    """
    Maximum number of ranked results to return. The response carries fewer when the index has fewer matches.
    """
    query: str = Field(..., examples=["linux kernel amd gpu suspend"], min_length=1)
    """
    The search query, phrased as the user or agent would ask it. Drives ranking and passage selection even when search_queries supplies a rewrite.
    """
    response: ResponseShape | None = None
    """
    Optional response shaping: verbosity preset and serialized-size budget.
    """
    scope: SearchScope | None = None
    """
    Which indexes to search. Omit it for the web index. Additive: existing clients are unaffected.
    """
    search_queries: list[str] | None = None
    """
    Caller-provided query rewrites. The first entry replaces query as the text sent to the search index; query still drives reranking and passage selection. All entries are visible to the server-side query rewriter.
    """
    session_id: UUID | None = None
    """
    Client session identifier (UUID). Groups related search, document, and feedback calls; equivalent to the X-Session-ID header. When omitted, the server generates one and echoes it back as session_id.
    """
    source_policy: dict[str, Any] | None = None
    """
    Domain allow/deny policy. Keys: include_domains (array of domains; with require_domain_match true, results outside them are dropped, and a single entry is also sent to the index as a site: operator), exclude_domains (array of domains whose results are always dropped), require_domain_match (boolean). Domains match their subdomains; a leading www. is ignored.
    """


class SearchResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    canonical_url: str
    description: str | None = None
    doc_id: str
    index: str | None = None
    labels: list[str] | None = None
    metadata: SearchResultMetadata | None = None
    mime: str | None = None
    passages: list[Passage] | None = None
    provenance: DocumentProvenance | None = None
    rank: int
    score: SearchScore | None = None
    snippet: str | None = None
    source_uri: str | None = None
    source_url: str | None = None
    title: str | None = None


class IntegrationResultsResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=["https://alpha.api.trycaesar.com/IntegrationResultsResponse.json"],
    )
    """
    A URL to the JSON Schema for this object.
    """
    access: Access | None = None
    next_cursor: str | None = None
    request_id: str
    results: list[IntegrationSearchResult] | None
    search_id: str
    total: int
    usage: Usage | None = None


class ResearchJobResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=["https://alpha.api.trycaesar.com/ResearchJobResponse.json"],
    )
    """
    A URL to the JSON Schema for this object.
    """
    access: Access | None = None
    completed_at: str | None = None
    created_at: str
    error: str | None = None
    """
    Present when status is failed.
    """
    id: str
    request_id: str
    result: ResearchResultResponse | None = None
    """
    Present when status is completed.
    """
    status: str
    """
    queued, running, completed, or failed.
    """


class SearchResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=["https://alpha.api.trycaesar.com/SearchResponse.json"],
    )
    """
    A URL to the JSON Schema for this object.
    """
    access: Access | None = None
    integration_results: IntegrationResultsSummary | None = None
    ranking: Ranking | None = None
    request_id: str
    results: list[SearchResult] | None
    search_id: str
    session_id: str
    truncated: bool | None = None
    usage: Usage | None = None
    warnings: list[Warning] | None = None
