# generated by datamodel-codegen:
#   filename:  openapi-public.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class CaptureHistoryEntry(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    capture_id: str
    capture_time: str
    content_digest: str
    content_format: str | None = None


class ContentRange(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    capture_id: str | None = None
    """
    Optional capture pin; a stale_range warning is returned when the latest capture differs.
    """
    max_chars: int | None = Field(None, ge=1)
    """
    Maximum characters for this range; overrides content.max_chars.
    """
    start_char: int | None = Field(None, ge=0)
    """
    Character offset to start content from.
    """


class Document(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    canonical_url: str
    content_digest: str | None = None
    doc_id: str
    first_seen_at: str
    headings: list[str] | None = None
    last_seen_at: str
    latest_capture_id: str | None = None
    meta_description: str | None = None
    published_at: str | None = None
    source_url: str
    title: str | None = None


class DocumentContent(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    char_count: int
    format: str
    selection: str
    start_char: int | None = None
    text: str
    truncated: bool


class Format(Enum):
    """
    Returned content format.
    """

    text = "text"
    markdown = "markdown"


class Selection(Enum):
    """
    Content selection strategy.
    """

    none = "none"
    query_relevant = "query_relevant"
    top_passages = "top_passages"
    passage_ids = "passage_ids"
    full_document = "full_document"


class DocumentContentRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    format: Format | None = "markdown"
    """
    Returned content format.
    """
    include_offsets: bool | None = None
    """
    Whether passage offsets should be included when available.
    """
    max_chars: int | None = Field(12000, ge=1)
    """
    Maximum content.text characters to return.
    """
    passage_ids: list[str] | None = None
    """
    Passage IDs to return when selection is passage_ids.
    """
    range: ContentRange | None = None
    """
    Continuation read: return content starting at a character offset of the same document.
    """
    selection: Selection | None = "query_relevant"
    """
    Content selection strategy.
    """


class DocumentProvenance(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    capture_id: str
    capture_time: str


class ErrorBody(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: str
    """
    Stable machine-readable error code.
    """
    details: dict[str, Any] | None = None
    """
    Optional structured error details.
    """
    message: str
    """
    Human-readable error message.
    """


class Type(Enum):
    """
    Envelope discriminator.
    """

    error = "error"


class ErrorEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=[
            "https://search-api-staging-779189860552.europe-west1.run.app/ErrorEnvelope.json"
        ],
    )
    """
    A URL to the JSON Schema for this object.
    """
    error: ErrorBody
    """
    Error details.
    """
    request_id: str
    """
    Server request identifier.
    """
    type: Type
    """
    Envelope discriminator.
    """


class FeedbackAgentContext(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    client_model: str | None = None
    """
    Calling model identifier.
    """
    task_type: str | None = None
    """
    Agent task type or evaluation bucket.
    """


class Passage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    char_end: int | None = None
    char_start: int | None = None
    doc_id: str
    ordinal: int
    passage_id: str
    section_heading: str | None = None
    section_path: list[str] | None = None
    text: str


class Ranking(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: str
    ranker_version: str
    score_scope: str


class RateLimit(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    limit_rps: int
    remaining: int
    reset_at: str


class OnExceed(Enum):
    """
    What to do when the budget binds: shed payload in the documented order, or fail with response_too_large.
    """

    shed = "shed"
    error = "error"


class ResponseBudget(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    max_chars_total: int | None = Field(None, ge=1)
    """
    Maximum serialized response size in characters. Roughly 4 characters per token.
    """
    on_exceed: OnExceed | None = "shed"
    """
    What to do when the budget binds: shed payload in the documented order, or fail with response_too_large.
    """


class Verbosity(Enum):
    """
    Field preset: ids_only (rank, doc_id, url, title), compact (adds snippet, score, key dates), standard (today's default), full (adds provenance).
    """

    ids_only = "ids_only"
    compact = "compact"
    standard = "standard"
    full = "full"


class ResponseShape(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    budget: ResponseBudget | None = None
    """
    Total serialized response budget in characters with deterministic shedding.
    """
    verbosity: Verbosity | None = "standard"
    """
    Field preset: ids_only (rank, doc_id, url, title), compact (adds snippet, score, key dates), standard (today's default), full (adds provenance).
    """


class SearchResultMetadata(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content_digest: str | None = None
    extracted_at: str | None = None
    first_seen_at: str | None = None
    last_crawled_at: str | None = None
    last_seen_at: str | None = None
    published_at: str | None = None


class SearchScore(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    value: float


class Usage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    approx_tokens: int
    bytes_returned: int
    requests: int


class Warning(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: str
    details: dict[str, Any] | None = None
    message: str


class Access(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    rate_limit: RateLimit
    tier: str


class DocumentResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=[
            "https://search-api-staging-779189860552.europe-west1.run.app/DocumentResponse.json"
        ],
    )
    """
    A URL to the JSON Schema for this object.
    """
    access: Access
    capture_history: list[CaptureHistoryEntry] | None = None
    content: DocumentContent | None = None
    doc: Document
    passages: list[Passage] | None = None
    provenance: DocumentProvenance | None = None
    request_id: str
    session_id: str
    usage: Usage | None = None
    warnings: list[Warning] | None = None


class FeedbackResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=[
            "https://search-api-staging-779189860552.europe-west1.run.app/FeedbackResponse.json"
        ],
    )
    """
    A URL to the JSON Schema for this object.
    """
    accepted: bool
    access: Access
    feedback_id: str
    request_id: str
    session_id: str
    usage: Usage | None = None


class SearchResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    canonical_url: str
    description: str | None = None
    doc_id: str
    metadata: SearchResultMetadata | None = None
    passages: list[Passage] | None = None
    provenance: DocumentProvenance | None = None
    rank: int
    score: SearchScore | None = None
    snippet: str | None = None
    source_url: str | None = None
    title: str | None = None


class SearchResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: AnyUrl | None = Field(
        None,
        alias="$schema",
        examples=[
            "https://search-api-staging-779189860552.europe-west1.run.app/SearchResponse.json"
        ],
    )
    """
    A URL to the JSON Schema for this object.
    """
    access: Access | None = None
    ranking: Ranking | None = None
    request_id: str
    results: list[SearchResult] | None
    search_id: str
    session_id: str
    truncated: bool | None = None
    usage: Usage | None = None
    warnings: list[Warning] | None = None
